name: CI-PR

on:
  pull_request:
  workflow_dispatch:

env:
  PLATFORMS: linux/amd64 #,linux/arm64
  REGISTRY: ghcr.io

jobs:
  ci-pr:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        # with:
        #   path: ${{ github.repository }}

      - name: Setup
        uses: ./.github/actions/setup
        with:
          registry: ${{ env.REGISTRY }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        uses: docker/build-push-action@bcafcacb16a39f128d818304e6c9c0c18556b85f # v7
        with:
          file: Containerfile
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:testing-${{ github.event.pull_request.number }}
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: ${{ env.PLATFORMS }}
          # provenance: false

      - name: Test - ansible
        run: |
          docker run ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:testing-${{ github.event.pull_request.number }} ansible --version

      - name: Test - molecule
        run: |
          docker run ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:testing-${{ github.event.pull_request.number }} molecule --version

      - name: Test - molecule converge
        run: |
          docker run --rm \
            -v "${{ github.workspace }}:/workspace" \
            -v /var/run/docker.sock:/var/run/docker.sock \
            -w /workspace \
            -e INPUT_MOLECULE_WORKING_DIR="tests/test-role" \
            -e INPUT_MOLECULE_COMMAND="converge" \
            -e ANSIBLE_REMOTE_TMP="/tmp/.ansible_remote_tmp" \
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:testing-${{ github.event.pull_request.number }}
